# Generated by Django 2.2 on 2020-11-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socdoc',
            name='loadsConnected',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
